# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('item_description', models.TextField(default='this is the description', max_length=100)),
                ('item_price', models.IntegerField(default=0)),
                ('item_price_sml', models.IntegerField(default=0)),
                ('item_price_md', models.IntegerField(default=0)),
                ('item_price_lrg', models.IntegerField(default=0)),
                ('item_url', models.TextField(default=' ')),
            ],
        ),
    ]
