# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20170110_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
